--- #YAML:1.0
name:               VKontakte-Standalone
version:            0.1
abstract:           Perl extension for creating standalone Vkontakte API applications
author:
    - Krylov Ivan <krylov.r00t@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    JSON:            0
    URI:             0
    WWW::Mechanize:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
